//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculateur {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Calculateur {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calculateur() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculateur.Calculateur", typeof(Calculateur).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elément attendu à la position {0} : {1}..
        /// </summary>
        internal static string EltAttPos {
            get {
                return ResourceManager.GetString("EltAttPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de syntaxe..
        /// </summary>
        internal static string ErreurSyntaxe {
            get {
                return ResourceManager.GetString("ErreurSyntaxe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fonction {0}() n&apos;est pas définie..
        /// </summary>
        internal static string FonctionIndefini {
            get {
                return ResourceManager.GetString("FonctionIndefini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FonctionNull.
        /// </summary>
        internal static string FonctionNull {
            get {
                return ResourceManager.GetString("FonctionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listefonc == null.
        /// </summary>
        internal static string listefoncEgaleNull {
            get {
                return ResourceManager.GetString("listefoncEgaleNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string MessageBoxErreur {
            get {
                return ResourceManager.GetString("MessageBoxErreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fonction {0}() attends {1} paramètres..
        /// </summary>
        internal static string ParametreIndefini {
            get {
                return ResourceManager.GetString("ParametreIndefini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La variable {0} n&apos;est pas définie..
        /// </summary>
        internal static string VariableIndefini {
            get {
                return ResourceManager.GetString("VariableIndefini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to variableNull.
        /// </summary>
        internal static string variableNull {
            get {
                return ResourceManager.GetString("variableNull", resourceCulture);
            }
        }
    }
}
